export const CAPTIONS = [
  "The VEINY Look",
  "Demon Back Incoming",
  "She Said Pink Today",
  "5kg Lion",
  "DND'd & Deployed",
  "Holy Framing",
  "Peek-A-Sun",
  "Bangalore Sakura",
  "Golden Hours",
  "Monochrome By Storm",
  "Pixel-Perfect Petals",
  "Ray-Cast At Dusk",
  "Contrast: Maxed",
  "No Off-Season",
  "Quadzilla",
  "Midnight Watch",
  "Pookie Said :p",
  "The Void Hour",
  "EXIT, But Pink",
  "Pit Walk",
  "City Loading...",
  "Chest GPS",
  "Iron + Amber",
  "Nutrient Palette",
  "Lane To Sun",
  "The Arnold Pose",
];
